version: '3'
services:

  pythondev:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/code/
    restart: unless-stopped
    command: tail -F anything #this cmd prevents docker from stopping the container